-- 014_cascade_audit_attachments.sql
-- Production hardening: add ON DELETE behavior to audit_logs.invoice_id and
-- attachments.invoice_id so mass deletes don't fail on FK violations.
--
-- attachments.invoice_id → ON DELETE CASCADE
--   (an attachment has no meaning without its invoice; cascade is safe)
--
-- audit_logs.invoice_id → ON DELETE SET NULL
--   (audit history must be preserved even if the invoice is purged)

-- Drop the existing FK constraints (name auto-generated by 006 migration)
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_invoice_id_fkey;
ALTER TABLE audit_logs
  ADD CONSTRAINT audit_logs_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;

-- attachments CASCADE was already set in 005 migration, but re-assert to be safe
ALTER TABLE attachments DROP CONSTRAINT IF EXISTS attachments_invoice_id_fkey;
ALTER TABLE attachments
  ADD CONSTRAINT attachments_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
