-- 001_seed_users.sql
-- Makuta Accounts Module users

INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 'Raju S', 'raju@makuta.in', '$2b$12$0i5rkv0VF23RVQZtTgAMbeiepEnyFHbH7lCCAnWBHtRc7Vh67ilpa', 'ho', NULL, 'Head Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 'Harsha', 'harsha@makuta.in', '$2b$12$tekkvzC7bCUYr2mQ1c51w.VMvl5AsGry6mjsCm0piZyq/CnYCH5vm', 'mgmt', NULL, 'Managing Director', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('c3d4e5f6-a7b8-4c9d-ae1f-2a3b4c5d6e7f', 'Ramana', 'ramana@makuta.in', '$2b$12$lYRAxpQOpXGmDmH5quj.neFmy65HhhkF4SZ44wFcw70joLoimaa8a', 'site', 'Nirvana', 'Site Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('d4e5f6a7-b8c9-4d0e-9f2a-3b4c5d6e7f80', 'Veerandhar', 'veerandhar@makuta.in', '$2b$12$bVtPEZhf/kdH8s/7YR/66eFYPKOypWUcahrKTXMZtqVvKs3s2m6Pm', 'site', 'Taranga', 'Site Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('e5f6a7b8-c9d0-4e1f-aa3b-4c5d6e7f8091', 'Madhu', 'madhu@makuta.in', '$2b$12$aYuXiBkM6WXRbC4zVsGFuOPlGdLYE.qqomKXSkNt3UbTYo3ma5082', 'site', 'Horizon', 'Site Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('f6a7b8c9-d0e1-4f2a-bb4c-5d6e7f809102', 'Madhu', 'madhu.gw@makuta.in', '$2b$12$u3cYRxLQ5kFoKPS8//S5wuo69V07FoaC0pkP7Wd8KoKTspgqqQnYa', 'site', 'Green Wood Villas', 'Site Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('07b8c9d0-e1f2-4a3b-8c5d-6e7f80910213', 'Ramana', 'ramana.aa@makuta.in', '$2b$12$jFOXlMp60WrbFkeMtwmLMOJqeY0RYH3gqiwpySLC3TTk.YUZ5uIg6', 'site', 'Aruna Arcade', 'Site Accountant', true, now(), now());
INSERT INTO users (id, name, email, password_hash, role, site, title, is_active, created_at, updated_at) VALUES ('18c9d0e1-f2a3-4b4c-9d6e-7f8091021324', 'Thanug', 'thanug@makuta.in', '$2b$12$jKqSdFCIiTlWenzXniiu3ONfLUrkPsyv2OQNrD9j4nZBpSd0LiRm2', 'site', 'Office', 'Site Accountant', true, now(), now());
